### ISSUE TITLE
No Soft On or Soft Off when using ST GUI but switch 1 works 

### ISSUE THREAD

**Issue by AndyHinch** [kjamsek/SmartThings#1]
When soft on and soft off is enabled for the switch but when using switch it does work. However the old Z Wave Metering Dimmer device handler does support soft on and soft off when using ST to control the light. Is there a way to have it use soft on and soft off if the param 5 is set to dimmer and param 66 is greater than 0

**Comment by kjamsek** [comment]
You can achieve the desired functionality on UI actions via editing the device handler, find all references to dimmingDuration and edit the values there according to this table:
![image](https://user-images.githubusercontent.com/8511275/36086540-5b920ba4-0fcd-11e8-9d9f-bbb409fd3f71.png)
